[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive", "env"] }
reqwest = { version = "0.12.24", features = ["blocking"] }

[dev-dependencies]
indoc = "2"